version: '3.3'
services:
  postgres:
    container_name: db
    image: postgres
    environment:
      POSTGRES_USER: pkt
      POSTGRES_PASSWORD: password
      PGDATA: /data/postgres
    volumes:
    - postgres:/data/postgres
    ports:
    - 5432:5432
    networks:
    - postgres
    restart: unless-stopped
  reddit-backend:
    image: prashant24062994/redit-backend
    container_name: reddit-backend
    ports:
    - 8080:8080
    networks:
    - spring
    - postgres
    environment:
    - SPRING_PROFILES_ACTIVE=prod
    - SPRING_DATASOURCE_URL=jdbc:mysql://db:5432/reddit_store?autoReconnect=true&useSSL=false
    - SPRING_DATASOURCE_USERNAME=pkt
    - SPRING_DATASOURCE_PASSWORD=password
    - SPRING_JPA_HIBERNATE_DDL-AUTO=update
    depends_on:
    - db
networks:
  postgres:
    driver: bridge
  spring:
    driver: bridge
volumes:
  postgres: null
  confmysql: null