version: '3.3'
services:
  db:
    image: mysql:5.7
    container_name: mysql-db-server
    restart: always
    environment:
      MYSQL_DATABASE: db
      MYSQL_ROOT_HOST: '%'
      MYSQL_USER: root
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: password
    ports:
    - 3306:3306
    expose:
    - '3306'
    volumes:
    - mysqldb:/var/lib/mysql
    - mysqlconf:/etc/mysql
    networks:
    - spring
    - mysql
networks:
  mysql:
    driver: bridge
  spring:
    driver: bridge
volumes:
  mysqldb: null
  mysqlconf: null