version: '3.3'
services:
  db:
    image: mysql:5.7
    container_name: mysql-db-server
    restart: always
    environment:
      MYSQL_DATABASE: db
      MYSQL_ROOT_HOST: '%'
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: password
    ports:
    - 3306:3306
    expose:
    - '3306'
    volumes:
    - mysqldb:/var/lib/mysql
    - mysqlconf:/etc/mysql
    networks:
    - spring
    - mysql
  mysql-workbench:
    image: lscr.io/linuxserver/mysql-workbench
    container_name: mysql-workbench
    environment:
    - PUID=1000
    - PGID=1000
    - TZ=Europe/London
    volumes:
    - /etc/mysql-config:/config
    ports:
    - 3000:3000
    cap_add:
    - IPC_LOCK
    restart: unless-stopped
    networks:
    - mysql
  reddit-backend:
    image: prashant24062994/redit-backend
    container_name: reddit-backend
    ports:
    - 8080:8080
    networks:
    - spring
    - mysql
    environment:
    - SPRING_PROFILES_ACTIVE=prod
    depends_on:
    - db
networks:
  mysql:
    driver: bridge
  spring:
    driver: bridge
volumes:
  mysqldb: null
  mysqlconf: null