server:
  port: 8080

app:
  url: http://reddit-backend:8080


jwt:
  expiration:
    time: 90000
  private:
    key: classpath:app.key
  public:
    key: classpath:app.pub

logging:
  level:
    org:
      hibernate:
        type:
          descriptor:
            sql: trace

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    password: password
    url: jdbc:postgresql://localhost:5432/reddit_store
    username: pkt
  jpa:
    hibernate:
      ddl-auto: create
    open-in-view: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true
    show-sql: true
  mail:
    host: smtp.mailtrap.io
    password: 647c175b3a708c
    port: 465
    protocol: smtp
    username: 3c97aa1b398e13
